### ISSUE TITLE
Is there some way to use CROSS_COMPILE or specify the cross-building toolchain to use?

### ISSUE THREAD

**Issue by Hamza281** [AdaloHQ/mobile-previewer#15]
Is there some way to use CROSS_COMPILE or specify the cross-building toolchain to use?

__Originally posted by @fabled in https://github.com/c3d/build/issues/1__

**Comment by danicunhac** [comment]
Would there be a specific use case for cross_compile in this project? I'm closing the issue due to inactivity but feel free to reopen if still needed.
